__all__ = ["SpotifyClient"]


from dataclasses import dataclass
from logging import Logger, getLogger

import requests

from src.config import Config
from src.data.music_brainz_client import MusicBrainzClient
from src.data.setlist_client import SetlistClient
from src.models.errors.artist_not_found_error import ArtistNotFoundError
from src.models.errors.authentication_error import AuthenticationError
from src.models.errors.setlist_not_found_error import SetlistNotFoundError
from src.models.spotify.setlist import Setlist
from src.models.spotify.setlist_track import SetlistTrack


@dataclass
class Track:
    name: str
    positions: list[int]

    def get_avg_position(self) -> int:
        return int(sum(self.positions) / len(self.positions))


class SpotifyClient:
    base_url = "https://api.spotify.com/v1"
    scope = (
        "user-read-private "
        "user-read-email "
        "playlist-modify-public "
        "playlist-modify-private"
    )
    state: str
    token: str
    logger: Logger

    def __init__(self, token: str) -> None:
        self.state = Config.spotify["state"]
        self.token = token
        self.logger = getLogger()

    @staticmethod
    def get_auth_url() -> str:
        query_args = {
            "response_type": "code",
            "client_id": Config.spotify["client_id"],
            "scope": SpotifyClient.scope,
            "redirect_uri": Config.spotify["redirect_uri"],
            "state": Config.spotify["state"],
        }

        query_str = ""

        for key, value in query_args.items():
            query_str += f"{key}={value}&"

        query_str = query_str[:-1]

        return f"https://accounts.spotify.com/authorize?{query_str}"

    def get_setlists(self, artist_name: str) -> list[Setlist]:
        self.logger.debug(f"Searching for {artist_name}'s setlists")
        artist_mbid = MusicBrainzClient().search_artist_by_name(artist_name)
        if artist_mbid is None:
            msg = f"Artist {artist_name} not found on MusicBrainz.org"
            self.logger.error(msg)
            raise ArtistNotFoundError(msg)

        setlists = SetlistClient().get_setlists_for_artist(artist_mbid["id"])
        setlists_with_tour_and_date = list(
            sorted(
                filter(lambda sl: "tour" in sl and "eventDate" in sl, setlists),
                key=lambda sl: sl["eventDate"],
                reverse=True,
            )
        )

        if len(setlists_with_tour_and_date) < 1:
            raise SetlistNotFoundError(
                f"No appropriate setlists found for {artist_name}"
            )

        return setlists_with_tour_and_date

    def get_most_recent_tour_name(self, setlists: list[Setlist]) -> str:
        most_recent_setlist = setlists[0]
        most_recent_tour = most_recent_setlist["tour"]["name"]

        return most_recent_tour

    def get_setlists_on_most_recent_tour(
        self, artist_name: str
    ) -> tuple[list[Setlist], str]:
        setlists = self.get_setlists(artist_name)
        tour = self.get_most_recent_tour_name(setlists)

        return list(filter(lambda sl: sl["tour"]["name"] == tour, setlists)), tour

    def get_tracklist_in_order(self, setlists: list[Setlist]) -> list[str]:
        tracks: dict[str, Track] = {}

        for setlist in setlists:
            for sl in setlist["sets"]["set"]:
                for idx, song in enumerate(sl["song"]):
                    song_name = song["name"]
                    if song_name in tracks:
                        tracks[song_name].positions.append(idx + 1)
                    else:
                        tracks[song_name] = Track(song_name, [idx + 1])

        track_list = list(filter(lambda t: t.name != "", tracks.values()))

        track_pos = {track.name: track.get_avg_position() for track in track_list}

        ordered_tracks = list(
            map(lambda t: t[0], sorted(track_pos.items(), key=lambda tp: tp[1]))
        )

        return ordered_tracks

    def get_user_id(self) -> str:
        url = f"{self.base_url}/me"

        response = requests.get(
            url,
            headers={
                "Accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.token}",
            },
        )

        response_data = response.json()

        if "id" not in response_data:
            raise AuthenticationError("Unable to Authorize Spotify")

        return response_data["id"]

    def create_playlist(self, artist_name: str, tour_name: str) -> str:
        """Returns the ID of the created playlist"""
        user_id = self.get_user_id()
        url = f"{self.base_url}/users/{user_id}/playlists"
        desc = (
            "Playlist Generated by "
            "https://github.com/Wraith29/dashboard?tab=readme-ov-file#setlist-generator"
        )

        response = requests.post(
            url,
            headers={
                "Accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.token}",
            },
            json={
                "name": f"{artist_name}: {tour_name}",
                "description": desc,
                "public": False,
            },
        )

        response_data = response.json()

        if response.status_code == 201 and "id" in response_data:
            return response_data["id"]

        # TODO: Improve the usability of this
        # TODO: Currently doesn't give any info to the user
        raise ValueError("Error creating playlist")

    # TODO: Make this perform better
    # Ideas:
    #  - query artist, then albums, and find tracks that way
    #  - consider multi-threading? is that even possible lol
    def get_track_ids(
        self, artist_name: str, track_names: list[str]
    ) -> list[SetlistTrack]:
        url = f"{self.base_url}/search"

        track_ids: list[SetlistTrack] = []

        for track in track_names:
            query = f"q=track:{track}+artist:{artist_name}&type=track"

            response = requests.get(
                f"{url}?{query}",
                headers={
                    "Accept": "application/json",
                    "Content-Type": "applications/json",
                    "Authorization": f"Bearer {self.token}",
                },
            )

            response_data = response.json()
            tracks = response_data["tracks"]

            if "items" not in tracks:
                # TODO: Make this more informative
                raise ValueError("Error Querying Spotify")

            items = tracks["items"]

            if len(items) < 1:
                continue

            track_ids.append({"name": track, "id": items[0]["id"]})

        return track_ids

    def add_tracks_to_playlist(
        self, artist_name: str, playlist_id: str, tracks: list[str]
    ) -> None:
        url = f"{self.base_url}/playlists/{playlist_id}/tracks"

        track_ids = self.get_track_ids(artist_name, tracks)

        track_uris = ",".join([f"spotify:track:{track["id"]}" for track in track_ids])

        response = requests.post(f"{url}?uris={track_uris}", headers={
            "Accept": "Application/json",
            "Authorization": f"Bearer {self.token}"
        })

        response_data = response.json()

        if "error" in response_data:
            self.logger.error(f"Error Creating Playlist: {response.json()["error"]["message"]}")

    def create_setlist_playlist_for_artist(self, artist_name: str) -> None:
        self.logger.debug(f"Creating playlist for {artist_name}")
        setlists, tour_name = self.get_setlists_on_most_recent_tour(artist_name)
        track_list = self.get_tracklist_in_order(setlists)

        playlist_id = self.create_playlist(artist_name, tour_name)

        self.add_tracks_to_playlist(artist_name, playlist_id, track_list)
